# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "6633c3eab82ad6fcb3ffc69a5f263b81" #web store
# client_id = "6011dc02944b02d6c4b8a3233901dffc" #app store
name = "Saitriq Wishlist"
application_url = "https://saitriq-wishlist.vercel.app"
embedded = true

[access_scopes]
scopes = "read_orders,read_themes"

[webhooks]
api_version = "2026-10"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

[auth]
redirect_urls = [ "https://saitriq-wishlist.vercel.app/auth/callback" ]

[app_proxy]
url = "https://saitriq-wishlist.vercel.app/apps/saitriq-wishlist"
subpath = "saitriq-wishlist"
prefix = "apps"

[build]
automatically_update_urls_on_dev = true
