name = "React Router"
roles = ["frontend", "backend"]
webhooks_path = "/webhooks/app/uninstalled"
[commands]
predev = "npm exec prisma generate"
dev = "npx prisma db push && npm exec react-router dev"
build = "npm exec prisma generate && npx prisma db push && npm exec react-router build"
